name: Release Build

on:
  push:
    tags:
      - 'v*' # v1.0.0 などのタグでトリガー

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build (Release)
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish -c Release -o publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: VRCSpeechToOSC
          path: publish/

  release:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: VRCSpeechToOSC
          path: publish/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: publish/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
